{% set name = "subrun" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/subrun-{{ version }}.tar.gz
  sha256: ad9903be46fff734d4d06291af3526b00010045de3dc8d13331d282f726aedb6

build:
  entry_points:
    - subrun = subrun.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - subrun
  commands:
    - pip check
    - subrun --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/subrun
  summary: Intuitive API to safely start and communicate with processes in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
